### ISSUE TITLE
Remove Exclamation Point from Offline First Homepage Title

### ISSUE THREAD

**Issue by bradley-holt** [janl/offlinefirst.org#163]
The title for the homepage is currently "Offline First!" (with an exclamation point). This leads some people to believe that the name of this approach is "Offline First!" (versus "Offline First") and should probably be changed.

**Comment by gr2m** [comment]
agreed 👍

**Comment by terichadbourne** [comment]
Just documenting that this shows up in the metadata that pulls into search engines, not on the website itself.  Pulls into Google search results of some subdomains but not others.  I assume the website is built to stack titles (like this "Camp - Offline First!" example if we don't tell an individual page to do something else.

![image](https://user-images.githubusercontent.com/19171465/29139726-ea0ae130-7d15-11e7-94a0-e2af8255ccdd.png)

I tried to find where the header metadata is coming from but am not having any luck because of how things are spread out in Jekyll. @gr2m or @kidfribble do you know off hand where I should look?

**Comment by terichadbourne** [comment]
Okay, I've done the thing that Bradley suspects will fix the problem, but I presume Google has to recrawl before we'd see a change in the search results. 

I just filled in this for OF and Camp sites to attempt to force a re-crawl: http://www.google.com/addurl/

Not closing this issue yet since I can't confirm it's been resolved.

**Comment by terichadbourne** [comment]
Good news! Google search results no longer shows the apostrophe, so I'll close this issue.

![image](https://user-images.githubusercontent.com/19171465/29288836-52bfb7aa-8108-11e7-91f9-121d5d294bcc.png)
